# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  web:
    image: ${USER}/docker-python-remote-debug:latest
    build: .
    entrypoint: python -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m pytest -lvx tests/test_user.py
    env_file:
      - ./.flaskenv
    environment:
      - DATABASE_URI=sqlite:////db/remote_debug.db
    volumes:
      - ./remote_debug:/code/remote_debug
      - ./db/:/db/
    ports:
      - "5600:5000"
      - "5678:5678"
